### ISSUE TITLE
Small/big change?

### ISSUE THREAD

**Issue by Darker-Ink** [somerandomcloud/termbot#3]
Just In case I'm making a Issue to insure that you are not working on this, 
I would like to know If I can add aliases Now it might seem like a small change and It kind of is but to most people it could be a big change so just making sure!

**Comment by 144reasons** [comment]
Hello, aliases are planned, and I would like to do them myself. To me it's very minor

**Comment by Darker-Ink** [comment]
> Hello, aliases are planned, and I would like to do them myself. To me it's very minor

ok!
